

using System.Collections;
using System.Drawing;

namespace ClipboardBuddy
{
    public static class DataStruct
    {
        // A StreamDeck XL has 32 keys (8 columns x 4 lines)
        public const int MaxColumnId = 7;
        public const int MaxRowId = 3;
        
        // The enum to select the color from
        // (list: https://learn.microsoft.com/fr-fr/dotnet/api/system.drawing.color?view=net-8.0)
        public static readonly Color[] UsefulColors =
        {
            Color.AliceBlue,
            Color.AntiqueWhite,
            Color.Aqua,
            Color.Aquamarine,
            Color.Azure,
            Color.Beige,
            Color.Bisque,
            //Color.Black,
            Color.BlanchedAlmond,
            //Color.Blue,
            //Color.BlueViolet,
            //Color.Brown,
            Color.BurlyWood,
            Color.CadetBlue,
            Color.Chartreuse,
            //Color.Chocolate,
            Color.Coral,
            Color.CornflowerBlue,
            Color.Cornsilk,
            //Color.Crimson,
            Color.Cyan,
            //Color.DarkBlue,
            //Color.DarkCyan,
            Color.DarkGoldenrod,
            Color.DarkKhaki,
            //Color.DarkMagenta,
            //Color.DarkOliveGreen,
            Color.DarkOrange,
            Color.DarkOrchid,
            //Color.DarkRed,
            Color.DarkSalmon,
            Color.DarkSeaGreen,
            //Color.DarkSlateBlue,
            //Color.DarkSlateGray,
            Color.DarkTurquoise,
            //Color.DarkViolet,
            //Color.DeepPink,
            Color.DeepSkyBlue,
            //Color.DimGray,
            Color.DodgerBlue,
            //Color.Firebrick,
            Color.FloralWhite,
            //Color.ForestGreen,
            //Color.Fuchsia,
            Color.Gainsboro,
            Color.GhostWhite,
            Color.Gold,
            Color.Goldenrod,
            //Color.Gray,
            //Color.Green,
            Color.GreenYellow,
            Color.Honeydew,
            Color.HotPink,
            Color.IndianRed,
            //Color.Indigo,
            Color.Ivory,
            Color.Khaki,
            Color.Lavender,
            Color.LavenderBlush,
            Color.LawnGreen,
            Color.LemonChiffon,
            Color.LightBlue,
            Color.LightCoral,
            Color.LightCyan,
            Color.LightGoldenrodYellow,
            Color.LightGray,
            Color.LightGreen,
            Color.LightPink,
            Color.LightSalmon,
            Color.LightSeaGreen,
            Color.LightSkyBlue,
            //Color.LightSlateGray,
            Color.LightSteelBlue,
            Color.LightYellow,
            Color.Lime,
            Color.LimeGreen,
            Color.Linen,
            Color.Magenta,
            //Color.Maroon,
            Color.MediumAquamarine,
            //Color.MediumBlue,
            Color.MediumOrchid,
            Color.MediumPurple,
            Color.MediumSeaGreen,
            //Color.MediumSlateBlue,
            Color.MediumSpringGreen,
            Color.MediumTurquoise,
            //Color.MediumVioletRed,
            //Color.MidnightBlue,
            Color.MintCream,
            Color.MistyRose,
            Color.Moccasin,
            Color.NavajoWhite,
            //Color.Navy,
            Color.OldLace,
            //Color.Olive,
            Color.OliveDrab,
            Color.Orange,
            //Color.OrangeRed,
            Color.Orchid,
            Color.PaleGoldenrod,
            Color.PaleGreen,
            Color.PaleTurquoise,
            Color.PaleVioletRed,
            Color.PapayaWhip,
            Color.PeachPuff,
            Color.Peru,
            Color.Pink,
            Color.Plum,
            Color.PowderBlue,
            //Color.Purple,
            //Color.Red,
            Color.RosyBrown,
            //Color.RoyalBlue,
            //Color.SaddleBrown,
            Color.Salmon,
            Color.SandyBrown,
            //Color.SeaGreen,
            Color.SeaShell,
            //Color.Sienna,
            Color.Silver,
            Color.SkyBlue,
            //Color.SlateBlue,
            //Color.SlateGray,
            Color.Snow,
            Color.SpringGreen,
            //Color.SteelBlue,
            Color.Tan,
            //Color.Teal,
            Color.Thistle,
            Color.Tomato,
            Color.Turquoise,
            Color.Violet,
            Color.Wheat,
            Color.White,
            Color.WhiteSmoke,
            Color.Yellow,
            Color.YellowGreen
        };

        // To avoid using the same color twice in a row (initialized for a 32 keys Stream Deck to be lazy)
        public static Hashtable ColorUsedMatrix = new Hashtable()
        {
            {"0x0", Color.Transparent},
            {"0x1", Color.Transparent},
            {"0x2", Color.Transparent},
            {"0x3", Color.Transparent},
            {"0x4", Color.Transparent},
            {"0x5", Color.Transparent},
            {"0x6", Color.Transparent},
            {"0x" + MaxColumnId, Color.Transparent},
            {"1x0", Color.Transparent},
            {"1x1", Color.Transparent},
            {"1x2", Color.Transparent},
            {"1x3", Color.Transparent},
            {"1x4", Color.Transparent},
            {"1x5", Color.Transparent},
            {"1x6", Color.Transparent},
            {"1x" + MaxColumnId, Color.Transparent},
            {"2x0", Color.Transparent},
            {"2x1", Color.Transparent},
            {"2x2", Color.Transparent},
            {"2x3", Color.Transparent},
            {"2x4", Color.Transparent},
            {"2x5", Color.Transparent},
            {"2x6", Color.Transparent},
            {"2x" + MaxColumnId, Color.Transparent},
            {MaxRowId + "x0", Color.Transparent},
            {MaxRowId + "x1", Color.Transparent},
            {MaxRowId + "x2", Color.Transparent},
            {MaxRowId + "x3", Color.Transparent},
            {MaxRowId + "x4", Color.Transparent},
            {MaxRowId + "x5", Color.Transparent},
            {MaxRowId + "x6", Color.Transparent},
            {MaxRowId + "x" + MaxColumnId, Color.Transparent}
        };
        
        public static Hashtable TextStorageMatrix = new Hashtable()
        {
            {"0x0", ""},
            {"0x1", ""},
            {"0x2", ""},
            {"0x3", ""},
            {"0x4", ""},
            {"0x5", ""},
            {"0x6", ""},
            {"0x" + MaxColumnId, ""},
            {"1x0", ""},
            {"1x1", ""},
            {"1x2", ""},
            {"1x3", ""},
            {"1x4", ""},
            {"1x5", ""},
            {"1x6", ""},
            {"1x" + MaxColumnId, ""},
            {"2x0", ""},
            {"2x1", ""},
            {"2x2", ""},
            {"2x3", ""},
            {"2x4", ""},
            {"2x5", ""},
            {"2x6", ""},
            {"2x" + MaxColumnId, ""},
            {MaxRowId + "x0", ""},
            {MaxRowId + "x1", ""},
            {MaxRowId + "x2", ""},
            {MaxRowId + "x3", ""},
            {MaxRowId + "x4", ""},
            {MaxRowId + "x5", ""},
            {MaxRowId + "x6", ""},
            {MaxRowId + "x" + MaxColumnId, ""}
        };
        
        public static Hashtable ConnectionMatrix = new Hashtable()
        {
            {"0x0", ""},
            {"0x1", ""},
            {"0x2", ""},
            {"0x3", ""},
            {"0x4", ""},
            {"0x5", ""},
            {"0x6", ""},
            {"0x" + MaxColumnId, ""},
            {"1x0", ""},
            {"1x1", ""},
            {"1x2", ""},
            {"1x3", ""},
            {"1x4", ""},
            {"1x5", ""},
            {"1x6", ""},
            {"1x" + MaxColumnId, ""},
            {"2x0", ""},
            {"2x1", ""},
            {"2x2", ""},
            {"2x3", ""},
            {"2x4", ""},
            {"2x5", ""},
            {"2x6", ""},
            {"2x" + MaxColumnId, ""},
            {MaxRowId + "x0", ""},
            {MaxRowId + "x1", ""},
            {MaxRowId + "x2", ""},
            {MaxRowId + "x3", ""},
            {MaxRowId + "x4", ""},
            {MaxRowId + "x5", ""},
            {MaxRowId + "x6", ""},
            {MaxRowId + "x" + MaxColumnId, ""}
        };
        
        public static Hashtable InitialImageNameMatrix = new Hashtable()
        {
            {"0x0", ""},
            {"0x1", ""},
            {"0x2", ""},
            {"0x3", ""},
            {"0x4", ""},
            {"0x5", ""},
            {"0x6", ""},
            {"0x" + MaxColumnId, ""},
            {"1x0", ""},
            {"1x1", ""},
            {"1x2", ""},
            {"1x3", ""},
            {"1x4", ""},
            {"1x5", ""},
            {"1x6", ""},
            {"1x" + MaxColumnId, ""},
            {"2x0", ""},
            {"2x1", ""},
            {"2x2", ""},
            {"2x3", ""},
            {"2x4", ""},
            {"2x5", ""},
            {"2x6", ""},
            {"2x" + MaxColumnId, ""},
            {MaxRowId + "x0", ""},
            {MaxRowId + "x1", ""},
            {MaxRowId + "x2", ""},
            {MaxRowId + "x3", ""},
            {MaxRowId + "x4", ""},
            {MaxRowId + "x5", ""},
            {MaxRowId + "x6", ""},
            {MaxRowId + "x" + MaxColumnId, ""}
        };
    }
}